linters:
  enable:
    - goimports
    - revive
    - gosec

linters-settings:
  errcheck:
    # report about not checking of errors in type assertions: `a := b.(MyStruct)`;
    # default is false: such cases aren't reported by default.
    check-type-assertions: true
  govet:
    # report about shadowed variables
    shadow: true

issues:
  exclude-use-default: false
  exclude-rules:
    - linters:
        - staticcheck
      # NOTE: TestMain での os.Exit 呼び出しは Go 1.15 で不要
      # see: https://golang.org/doc/go1.15#testing
      text: 'SA3000:'
    - linters:
        - revive
      # NOTE: パッケージコメントを適宜追加するのは開発効率が悪くなるという判断よりコメントは不要
      text: 'package-comments: should have a package comment'
